apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../config
  - ../../base/redis

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: redis-config
  behavior: merge
  envs:
  - application.properties
  options:
    disableNameSuffixHash: true
- name: redis-config-gen
  literals:
  - doubao=baby
secretGenerator:
  - name: db-secret
    files:
      - "db.username"
      - "db.password"
#namePrefix: mall-
#
#nameSuffix: -v2

#patchesStrategicMerge:
#  - hpa.yaml
#
#patches:
#  - path: patch.yaml
#    target:
#      kind: Deployment
#  - patch: |-
#      - op: replace
#        path: /spec/template/spec/containers/0/name
#        value: bigredis
#      - op: replace
#        path: /spec/template/spec/containers/0/ports/0/containerPort
#        value: 8001
#    target:
#      kind: Deployment
##  - path: patch.json
##    target:
##      kind: Deployment
#
#patchesJson6902:
#  - path: patch.json
#    target:
#      kind: Deployment
#      version: v1
#      name: redis

